version: '2'
services:
  mysql:
    image: percona/percona-server:5.7
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 256M
        reservations:
          cpus: '1'
          memory: 128M
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - wp-data:/var/lib/mysql
    networks:
      - net_data
  wordpress:
    image: tscangussu/wordpress:4.9-php7.1-fpm-alpine
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 256M
        reservations:
          cpus: '1'
          memory: 128M
    environment:
      WP_DB_HOST: mysql
      WP_DB_USER: wordpress
      WP_DB_PASSWORD: wordpress
      WP_DB_NAME: wordpress
      WP_TABLE_PREFIX: zp
    depends_on:
      - mysql
    volumes:
      - wp-files:/var/www/
    networks:
      - net_app
      - net_data
  nginx:
    image: nginx:1.13-alpine
    configs:
      - source: nginx_site_conf
        target: /etc/nginx/conf.d/default.conf
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 64M
        reservations:
          cpus: '1'
          memory: 32M
    depends_on:
      - wordpress
      - traefik
    labels:
      - traefik.enable=true
      - traefik.backend=nginx
      - traefik.frontend.rule=Host:local.zenpress.com.br
      - traefik.docker.network=net_proxy
      - traefik.port=80
    volumes:
      - wp-files:/var/www/
    networks:
      - net_app
      - net_proxy
configs:
  nginx_site_conf:
    file: ./config/nginx/default.conf
volumes:
  wp-data:
  wp-files:
networks:
  net_proxy:
  net_app:
  net_data:
