version: '2'
services:
  nginx:
    volumes:
      - ./secrets/ssl/local.key:/etc/ssl/local.key
      - ./secrets/ssl/local.crt:/etc/ssl/local.crt
  wordpress:
    volumes:
      - ./config/wordpress/wp-config-local.php:/var/www/wp-config-local.php
      - ./config/wordpress/docker-wp-entrypoint.sh:/var/www/docker-wp-entrypoint.sh
    environment:
      WP_ENV: 'dev'
    entrypoint: /var/www/docker-wp-entrypoint.sh
    command: ["php-fpm7"]
