version: '2'
services:
  mysql:
    image: percona/percona-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    cpuset: "5"
    mem_limit: 256m
    mem_reservation: 128m
    volumes:
      - data:/var/lib/mysql
    networks:
      - net_data
  wordpress:
    image: tscangussu/wordpress:4.9-php7.1-fpm-alpine
    environment:
      WP_DB_HOST: mysql
      WP_DB_USER: wordpress
      WP_DB_PASSWORD: wordpress
      WP_DB_NAME: wordpress
      WP_TABLE_PREFIX: zp
    depends_on:
      - mysql
    cpuset: "5"
    mem_limit: 256m
    mem_reservation: 128m
    volumes:
      - app:/var/www/
    networks:
      - net_app
      - net_data
  nginx:
    image: nginx:1.13-alpine
    depends_on:
      - wordpress
    labels:
      - traefik.enable=true
      - traefik.backend=nginx
      - traefik.frontend.rule=Host:local.zenpress.com.br
      # traefik needs network's name with project's name
      - traefik.docker.network=zendock_net_proxy
    cpuset: "5"
    mem_limit: 32m
    mem_reservation: 16m
    volumes:
      - app:/var/www/
    networks:
      - net_app
networks:
  net_app:
  net_data:
volumes:
  data:
  app:
