debug = false
checkNewVersion = true
logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
# only for development
    [[entryPoints.https.tls.certificates]]
      CertFile = "/etc/ssl/local.crt"
      KeyFile = "/etc/ssl/local.key"

[retry]

################################################################
# Docker configuration backend
################################################################

# Enable Docker configuration backend.
[docker]
# Docker server endpoint. Can be a tcp or a unix socket endpoint. Required
endpoint = "unix:///var/run/docker.sock"
# Default domain used. Can be overridden by setting the "traefik.domain"
# label on a container.Required
domain = "docker.localhost"
# Enable watch docker changes. Optional
watch = true
# Expose containers by default in Traefik.
# If set to false, containers that don't have `traefik.enable=true` will
# be ignored. Optional. Default: true
exposedbydefault = false
# Use Swarm Mode services as data provider. Optional. Default: false
swarmmode = false

# only with valid domain
#[acme]
#email = "thiago.cangussu@gmail.com"
#storage = "acme.json"
#entryPoint = "https"
#OnHostRule = true

#    Uncomment the line to run on the staging Let's Encrypt server.
#    Leave comment to go to prod.
#caServer = "https://acme-staging.api.letsencrypt.org/directory"

# Enable web backend.
[web]
# Web administration port. Required. Default: ":8080"
address = ":8080"
# Set REST API to read-only mode. Optional. Default: false
readOnly = true
